# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.georecords_coordinates import GeorecordsCoordinates  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, image: str=None, coordinates: GeorecordsCoordinates=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param name: The name of this InlineResponse200.  # noqa: E501
        :type name: str
        :param image: The image of this InlineResponse200.  # noqa: E501
        :type image: str
        :param coordinates: The coordinates of this InlineResponse200.  # noqa: E501
        :type coordinates: GeorecordsCoordinates
        """
        self.swagger_types = {
            'name': str,
            'image': str,
            'coordinates': GeorecordsCoordinates
        }

        self.attribute_map = {
            'name': 'name',
            'image': 'image',
            'coordinates': 'coordinates'
        }
        self._name = name
        self._image = image
        self._coordinates = coordinates

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this InlineResponse200.

        Name of the record.  # noqa: E501

        :return: The name of this InlineResponse200.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InlineResponse200.

        Name of the record.  # noqa: E501

        :param name: The name of this InlineResponse200.
        :type name: str
        """

        self._name = name

    @property
    def image(self) -> str:
        """Gets the image of this InlineResponse200.

        URL to the image.  # noqa: E501

        :return: The image of this InlineResponse200.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image: str):
        """Sets the image of this InlineResponse200.

        URL to the image.  # noqa: E501

        :param image: The image of this InlineResponse200.
        :type image: str
        """

        self._image = image

    @property
    def coordinates(self) -> GeorecordsCoordinates:
        """Gets the coordinates of this InlineResponse200.


        :return: The coordinates of this InlineResponse200.
        :rtype: GeorecordsCoordinates
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates: GeorecordsCoordinates):
        """Sets the coordinates of this InlineResponse200.


        :param coordinates: The coordinates of this InlineResponse200.
        :type coordinates: GeorecordsCoordinates
        """

        self._coordinates = coordinates
